version: "3.7"
services:
  notebook:
    image: jupyter/pyspark-notebook:spark-3.1.2
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    environment:
      - MARQUEZ_HOST=marquez_api
      - MARQUEZ_PORT=5000
    links:
      - "api:marquez"
    depends_on:
      - api

# Marquez as an OpenLineage Client
  api:
    image: marquezproject/marquez:0.20.0
    container_name: marquez_api
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
    links:
      - "db:postgres"
    depends_on:
      - db
    entrypoint: [ "./wait-for-it.sh", "db:5432", "--", "./entrypoint.sh" ]

  web:
    image: "marquezproject/marquez-web"
    container_name: marquez_web
    environment:
      - MARQUEZ_HOST=marquez_api
      - MARQUEZ_PORT=5000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api

  db:
    image: postgres:12.1
    container_name: marquez_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]